<a href="https://colab.research.google.com/github/dipeshMahakali/reinforcement_model/blob/main/PytorchManualTrainingPipelineCreate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
# Code flowTraining pipeline
#    Load The DataSet
#    Data Preprocessing
#    Training Process:
#           Create Model
#           Forward Pass
#           Loss Calculation
#           Back Progation
#           Parameter Update
#     Purchase Evaluation

df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
print(df.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0
1    842517         M        20.57         17.77          132.90     1326.0
2  84300903         M        19.69         21.25          130.00     1203.0
3  84348301         M        11.42         20.38           77.58      386.1
4  84358402         M        20.29         14.34          135.10     1297.0

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710
1          0.08474           0.07864          0.0869              0.07017
2          0.10960           0.15990          0.1974              0.12790
3          0.14250           0.28390          0.2414              0.10520
4          0.10030           0.13280          0.1980              0.10430

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622
1  ...          23.41           158.80      1956.0            0.1238
2  ...          25.53           152.50      1709.0            0.1444
3  ...          26.50            98.87       567.7            0.2098
4  ...          16.67           152.20      1575.0            0.1374

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601
1             0.1866           0.2416                0.1860          0.2750
2             0.4245           0.4504                0.2430          0.3613
3             0.8663           0.6869                0.2575          0.6638
4             0.2050           0.4000                0.1625          0.2364

   fractal_dimension_worst  Unnamed: 32
0                  0.11890          NaN
1                  0.08902          NaN
2                  0.08758          NaN
3                  0.17300          NaN
4                  0.07678          NaN

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id','Unnamed: 32'], inplace = True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Splitting Training and Testing Data

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

Scaling Data

In [6]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [7]:
x_train

array([[-0.12086155, -0.38298004, -0.17105777, ..., -0.35788401,
        -0.62044255, -0.79171192],
       [ 0.24228793, -0.88302733,  0.22071451, ...,  0.3541944 ,
         0.09198166, -0.01019666],
       [ 1.25072608,  0.22975397,  1.21732819, ...,  0.52190224,
        -0.90966064, -0.53473722],
       ...,
       [ 1.47140923, -0.25620748,  1.42352413, ...,  1.67319387,
         1.13120597, -0.33071825],
       [-0.70748762,  1.22515327, -0.71808345, ..., -1.00182166,
         0.5658418 , -0.91155913],
       [-0.31361012,  0.69223902, -0.40353357, ..., -1.58941855,
        -0.98482466, -1.41435996]])

In [8]:
y_train

483    B
227    B
27     M
136    B
428    B
      ..
145    B
133    B
282    M
305    B
178    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding (To Change Lables into numeric value)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
y_train

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

# Numpy Arrays to Pytorch tensors

In [10]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
x_train_tensor.shape

torch.Size([455, 30])

In [12]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [22]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad = True)
    self.bais = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bais
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

# Important Parameters

In [24]:
learning_rate = 0.1
epochs = 25

# Training pipeline

In [28]:
# create model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_train_tensor)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward pass
  loss.backward()

  # Parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bais -= learning_rate * model.bais.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bais.grad.zero_()

  # Print loss in each epoch
  print(f'epoch: {epoch + 1}, loss: {loss.item()}')

epoch: 1, loss: 3.6221210973502043
epoch: 2, loss: 3.498827170254971
epoch: 3, loss: 3.3715624017934127
epoch: 4, loss: 3.237010923886058
epoch: 5, loss: 3.096978974591931
epoch: 6, loss: 2.9550727152027547
epoch: 7, loss: 2.8132379054306
epoch: 8, loss: 2.6690434109905006
epoch: 9, loss: 2.5213401151094335
epoch: 10, loss: 2.3682464488906643
epoch: 11, loss: 2.21664831090879
epoch: 12, loss: 2.058352930416925
epoch: 13, loss: 1.9012096004067431
epoch: 14, loss: 1.7468890885232162
epoch: 15, loss: 1.5984111159625138
epoch: 16, loss: 1.4578800001625232
epoch: 17, loss: 1.3279626647570477
epoch: 18, loss: 1.2132252060308997
epoch: 19, loss: 1.1146113192214955
epoch: 20, loss: 1.0323521569935514
epoch: 21, loss: 0.9657858727640427
epoch: 22, loss: 0.9133108629358407
epoch: 23, loss: 0.8725898610802548
epoch: 24, loss: 0.8410546367474061
epoch: 25, loss: 0.8164116546138771

In [29]:
model.bais

tensor([-0.1254], dtype=torch.float64, requires_grad=True)

# Evaluation

In [31]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy of Model: {accuracy}")

Accuracy of Model: 0.5107725262641907